changelog:
  categories:
    - title: New Features
      labels:
        - feat
        - feature
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Documentation
      labels:
        - docs
    - title: Other Changes
      labels:
        - "*"
